server:
    port: 9000
    contextPath:

spring:
    profiles:
        active: production

    thymeleaf:
        cache: true

    jade4j:
        caching: true

    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/otadb
      username: root
      password: root

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: update
      show_sql: false

  
multipart:
    enabled: true
    fileSizeThreshold: 0
    location: 
    maxFileSize: 12Mb
    maxRequestSize: 12Mb      
      
      
      
